{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7d0d5d67-98a2-459c-bc36-4e37da7c8c80",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "053d9d98-0a21-445d-92ca-a270e474ff50",
   "metadata": {},
   "outputs": [],
   "source": [
    "API_URL = \"http://127.0.0.1:3000/predict/\"\n",
    "cap = cv2.VideoCapture(-1)  \n",
    "frame_rate = 30  \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e74ba2d1-caea-4896-9682-c11b5404f091",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Prediction: read, Confidence: 0.26666666666666666\n",
      "Prediction: read, Confidence: 0.26\n",
      "Prediction: read, Confidence: 0.26666666666666666\n",
      "Prediction: read, Confidence: 0.26666666666666666\n",
      "Prediction: read, Confidence: 0.26666666666666666\n",
      "Prediction: read, Confidence: 0.26666666666666666\n",
      "Prediction: read, Confidence: 0.25333333333333335\n",
      "Prediction: read, Confidence: 0.25333333333333335\n",
      "Prediction: read, Confidence: 0.25333333333333335\n",
      "Prediction: read, Confidence: 0.25333333333333335\n",
      "Prediction: read, Confidence: 0.25333333333333335\n",
      "Prediction: read, Confidence: 0.25333333333333335\n",
      "Prediction: read, Confidence: 0.25333333333333335\n",
      "Prediction: thank you, Confidence: 0.24666666666666667\n",
      "Prediction: thank you, Confidence: 0.24666666666666667\n",
      "Prediction: thank you, Confidence: 0.24666666666666667\n",
      "Prediction: thank you, Confidence: 0.24666666666666667\n",
      "Prediction: eat, Confidence: 0.16666666666666666\n",
      "Prediction: hello, Confidence: 0.74\n",
      "Prediction: hello, Confidence: 0.7133333333333334\n",
      "Prediction: hello, Confidence: 0.7266666666666667\n",
      "Prediction: hello, Confidence: 0.7066666666666667\n",
      "Prediction: hello, Confidence: 0.7066666666666667\n",
      "Prediction: hello, Confidence: 0.8\n",
      "Prediction: hello, Confidence: 0.7733333333333333\n",
      "Prediction: hello, Confidence: 0.78\n",
      "Prediction: hello, Confidence: 0.8933333333333333\n",
      "Prediction: hello, Confidence: 0.9266666666666666\n",
      "Prediction: hello, Confidence: 0.9266666666666666\n",
      "Prediction: hello, Confidence: 0.9466666666666667\n",
      "Prediction: hello, Confidence: 0.9266666666666666\n",
      "Prediction: hello, Confidence: 0.92\n",
      "Prediction: hello, Confidence: 0.9333333333333333\n",
      "Prediction: learn, Confidence: 0.24\n",
      "Prediction: read, Confidence: 0.26666666666666666\n",
      "Prediction: read, Confidence: 0.2733333333333333\n",
      "Prediction: read, Confidence: 0.2866666666666667\n",
      "Prediction: read, Confidence: 0.29333333333333333\n",
      "Prediction: read, Confidence: 0.2866666666666667\n",
      "Prediction: read, Confidence: 0.2733333333333333\n",
      "Prediction: read, Confidence: 0.26666666666666666\n",
      "Prediction: read, Confidence: 0.26666666666666666\n",
      "Prediction: read, Confidence: 0.26\n",
      "Prediction: read, Confidence: 0.25333333333333335\n",
      "Prediction: read, Confidence: 0.38\n",
      "Prediction: please, Confidence: 0.2\n",
      "Prediction: X, Confidence: 0.26666666666666666\n",
      "Prediction: phone, Confidence: 0.54\n",
      "Prediction: phone, Confidence: 0.58\n",
      "Prediction: A, Confidence: 0.34\n",
      "Prediction: A, Confidence: 0.3333333333333333\n",
      "Prediction: A, Confidence: 0.48\n",
      "Prediction: read, Confidence: 0.38666666666666666\n",
      "Prediction: please, Confidence: 0.2\n",
      "Prediction: please, Confidence: 0.2\n",
      "Prediction: please, Confidence: 0.2\n",
      "Prediction: please, Confidence: 0.2\n",
      "Prediction: read, Confidence: 0.32666666666666666\n",
      "Prediction: read, Confidence: 0.2733333333333333\n",
      "Prediction: read, Confidence: 0.21333333333333335\n",
      "Prediction: read, Confidence: 0.22666666666666666\n",
      "Prediction: read, Confidence: 0.21333333333333335\n",
      "Prediction: read, Confidence: 0.22\n",
      "Prediction: read, Confidence: 0.20666666666666667\n",
      "Prediction: please, Confidence: 0.2\n",
      "Prediction: love, Confidence: 0.22\n",
      "Prediction: have, Confidence: 0.38666666666666666\n",
      "Prediction: school, Confidence: 0.26\n",
      "Prediction: house, Confidence: 0.22666666666666666\n",
      "Prediction: school, Confidence: 0.23333333333333334\n",
      "Prediction: house, Confidence: 0.22666666666666666\n",
      "Prediction: house, Confidence: 0.26666666666666666\n",
      "Prediction: house, Confidence: 0.24666666666666667\n",
      "Prediction: house, Confidence: 0.22666666666666666\n",
      "Prediction: house, Confidence: 0.26\n",
      "Prediction: school, Confidence: 0.24\n",
      "Prediction: house, Confidence: 0.2866666666666667\n",
      "Prediction: thank you, Confidence: 0.6133333333333333\n",
      "Prediction: please, Confidence: 0.38666666666666666\n",
      "Prediction: read, Confidence: 0.35333333333333333\n",
      "Prediction: read, Confidence: 0.5666666666666667\n",
      "Prediction: read, Confidence: 0.37333333333333335\n",
      "Prediction: read, Confidence: 0.36\n",
      "Prediction: read, Confidence: 0.3333333333333333\n",
      "Prediction: read, Confidence: 0.36666666666666664\n",
      "Prediction: read, Confidence: 0.4\n",
      "Prediction: read, Confidence: 0.47333333333333333\n",
      "Prediction: read, Confidence: 0.44666666666666666\n",
      "Prediction: read, Confidence: 0.5\n",
      "Prediction: read, Confidence: 0.44\n",
      "Prediction: read, Confidence: 0.5066666666666667\n",
      "Prediction: please, Confidence: 0.30666666666666664\n",
      "Prediction: read, Confidence: 0.48\n",
      "Prediction: learn, Confidence: 0.6533333333333333\n",
      "Prediction: learn, Confidence: 0.5333333333333333\n",
      "Prediction: learn, Confidence: 0.5466666666666666\n",
      "Prediction: learn, Confidence: 0.5266666666666666\n",
      "Prediction: learn, Confidence: 0.5333333333333333\n",
      "Prediction: learn, Confidence: 0.54\n",
      "Prediction: learn, Confidence: 0.5533333333333333\n",
      "Prediction: learn, Confidence: 0.58\n",
      "Prediction: learn, Confidence: 0.4\n",
      "Prediction: house, Confidence: 0.3\n",
      "Prediction: phone, Confidence: 0.17333333333333334\n",
      "Prediction: book, Confidence: 0.15333333333333332\n",
      "Prediction: book, Confidence: 0.2\n",
      "Prediction: book, Confidence: 0.22\n",
      "Prediction: book, Confidence: 0.21333333333333335\n",
      "Prediction: book, Confidence: 0.26\n",
      "Prediction: book, Confidence: 0.26\n",
      "Prediction: book, Confidence: 0.28\n",
      "Prediction: book, Confidence: 0.28\n",
      "Prediction: book, Confidence: 0.3\n",
      "Prediction: book, Confidence: 0.23333333333333334\n",
      "Prediction: thank you, Confidence: 0.17333333333333334\n",
      "Prediction: thank you, Confidence: 0.48\n",
      "Prediction: open, Confidence: 0.24\n",
      "Prediction: book, Confidence: 0.18666666666666668\n",
      "Prediction: book, Confidence: 0.16\n",
      "Prediction: book, Confidence: 0.26\n",
      "Prediction: book, Confidence: 0.25333333333333335\n",
      "Prediction: book, Confidence: 0.30666666666666664\n",
      "Prediction: house, Confidence: 0.24666666666666667\n",
      "Prediction: open, Confidence: 0.46\n",
      "Prediction: open, Confidence: 0.42\n",
      "Prediction: open, Confidence: 0.46\n",
      "Prediction: open, Confidence: 0.48\n",
      "Prediction: open, Confidence: 0.3933333333333333\n",
      "Prediction: open, Confidence: 0.37333333333333335\n",
      "Prediction: open, Confidence: 0.4\n",
      "Prediction: open, Confidence: 0.44666666666666666\n",
      "Prediction: thank you, Confidence: 0.2866666666666667\n",
      "Prediction: read, Confidence: 0.26\n",
      "Prediction: read, Confidence: 0.5533333333333333\n",
      "Prediction: read, Confidence: 0.34\n",
      "Prediction: read, Confidence: 0.29333333333333333\n",
      "Prediction: read, Confidence: 0.36666666666666664\n",
      "Prediction: read, Confidence: 0.36666666666666664\n",
      "Prediction: read, Confidence: 0.36666666666666664\n",
      "Prediction: read, Confidence: 0.2866666666666667\n",
      "Prediction: please, Confidence: 0.25333333333333335\n",
      "Prediction: read, Confidence: 0.29333333333333333\n",
      "Prediction: read, Confidence: 0.29333333333333333\n",
      "Prediction: read, Confidence: 0.30666666666666664\n",
      "Prediction: please, Confidence: 0.2\n",
      "Prediction: read, Confidence: 0.3\n",
      "Prediction: B, Confidence: 0.25333333333333335\n",
      "Prediction: thank you, Confidence: 0.36\n",
      "Prediction: B, Confidence: 0.3466666666666667\n",
      "Prediction: B, Confidence: 0.5933333333333334\n",
      "Prediction: B, Confidence: 0.62\n",
      "Prediction: B, Confidence: 0.6066666666666667\n",
      "Prediction: B, Confidence: 0.5333333333333333\n",
      "Prediction: B, Confidence: 0.38\n",
      "Prediction: thank you, Confidence: 0.3\n",
      "Prediction: B, Confidence: 0.5133333333333333\n",
      "Prediction: B, Confidence: 0.41333333333333333\n",
      "Prediction: water, Confidence: 0.4266666666666667\n",
      "Prediction: B, Confidence: 0.5133333333333333\n",
      "Prediction: B, Confidence: 0.5333333333333333\n",
      "Prediction: B, Confidence: 0.5933333333333334\n",
      "Prediction: B, Confidence: 0.3933333333333333\n",
      "Prediction: B, Confidence: 0.34\n",
      "Prediction: B, Confidence: 0.32666666666666666\n",
      "Prediction: hello, Confidence: 0.3333333333333333\n",
      "Prediction: hello, Confidence: 0.36666666666666664\n",
      "Prediction: hello, Confidence: 0.36666666666666664\n",
      "Prediction: hello, Confidence: 0.37333333333333335\n",
      "Prediction: hello, Confidence: 0.36\n",
      "Prediction: hello, Confidence: 0.3466666666666667\n",
      "Prediction: hello, Confidence: 0.35333333333333333\n",
      "Prediction: A, Confidence: 0.58\n",
      "Prediction: P, Confidence: 0.3\n",
      "Prediction: P, Confidence: 0.26666666666666666\n",
      "Prediction: C, Confidence: 0.2866666666666667\n",
      "Prediction: B, Confidence: 0.3466666666666667\n",
      "Prediction: B, Confidence: 0.37333333333333335\n",
      "Prediction: hello, Confidence: 0.38666666666666666\n",
      "Prediction: B, Confidence: 0.5933333333333334\n",
      "Prediction: B, Confidence: 0.62\n",
      "Prediction: B, Confidence: 0.6733333333333333\n",
      "Prediction: B, Confidence: 0.66\n",
      "Prediction: B, Confidence: 0.6733333333333333\n",
      "Prediction: B, Confidence: 0.68\n",
      "Prediction: B, Confidence: 0.6666666666666666\n",
      "Prediction: B, Confidence: 0.6733333333333333\n",
      "Prediction: B, Confidence: 0.6466666666666666\n",
      "Prediction: B, Confidence: 0.66\n",
      "Prediction: B, Confidence: 0.6066666666666667\n",
      "Prediction: B, Confidence: 0.6\n",
      "Prediction: B, Confidence: 0.5866666666666667\n",
      "Prediction: O, Confidence: 0.7333333333333333\n",
      "Prediction: please, Confidence: 0.2\n",
      "Prediction: eat, Confidence: 0.18\n",
      "Prediction: read, Confidence: 0.37333333333333335\n",
      "Prediction: read, Confidence: 0.36666666666666664\n",
      "Prediction: read, Confidence: 0.5\n",
      "Prediction: read, Confidence: 0.5066666666666667\n",
      "Prediction: read, Confidence: 0.4\n",
      "Prediction: read, Confidence: 0.42\n",
      "Prediction: read, Confidence: 0.37333333333333335\n",
      "Prediction: read, Confidence: 0.41333333333333333\n",
      "Prediction: read, Confidence: 0.4066666666666667\n",
      "Prediction: read, Confidence: 0.4533333333333333\n",
      "Prediction: thank you, Confidence: 0.23333333333333334\n",
      "Prediction: have, Confidence: 0.32\n",
      "Prediction: house, Confidence: 0.3933333333333333\n",
      "Prediction: house, Confidence: 0.46\n",
      "Prediction: house, Confidence: 0.36666666666666664\n",
      "Prediction: house, Confidence: 0.34\n",
      "Prediction: go, Confidence: 0.47333333333333333\n",
      "Prediction: go, Confidence: 0.21333333333333335\n",
      "Prediction: house, Confidence: 0.24666666666666667\n",
      "Prediction: house, Confidence: 0.2866666666666667\n",
      "Prediction: thank you, Confidence: 0.7666666666666667\n",
      "Prediction: read, Confidence: 0.21333333333333335\n",
      "Prediction: eat, Confidence: 0.16666666666666666\n",
      "Prediction: please, Confidence: 0.23333333333333334\n",
      "Prediction: please, Confidence: 0.31333333333333335\n",
      "Prediction: drink, Confidence: 0.18\n",
      "Prediction: please, Confidence: 0.24666666666666667\n",
      "Prediction: hello, Confidence: 0.23333333333333334\n",
      "Error occurred: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda85e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa950>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaba30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f001c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01060>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda81c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8a60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00940>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465cf10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8df0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab580>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f003a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8640>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8880>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465de40>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f012a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda82e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8e20>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabc10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f012d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8100>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8460>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda89a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8760>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00df0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f017b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda92a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa950>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab820>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00730>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00a60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabc70>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaaa10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaba60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa980>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f010c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01f00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8070>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda84c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabc10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00520>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabb20>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaba90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabf70>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8e80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8280>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8130>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabe50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00430>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c070>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8a30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabc10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda84c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00760>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00b80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa980>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8a60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8a00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6f7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6f7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaada0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda83d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda9000>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f012d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda87c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8df0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda85b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f010c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6d000>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda88b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda83d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda82b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabf40>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab760>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda88b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaac50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465e650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00d90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00d30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6f7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda91b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda9060>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa920>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00d30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01f00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00760>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6fa00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8070>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda9300>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda9090>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda85b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f018a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f02230>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd4b700>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab580>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab730>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda84f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda82b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f020e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa890>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda83d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f017e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01630>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab820>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaba00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda87f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab520>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f014b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01d50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8d00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaba00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaad70>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465d630>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f016f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465feb0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab460>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaada0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa800>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda92a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01180>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaac80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabd90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8970>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6fa00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00220>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01f60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6d000>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda88b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8730>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda84f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00190>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8760>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8520>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda9210>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8970>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6f820>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00040>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f003d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ced787e20>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda83a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabd00>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda93c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda80a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f003d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01330>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8310>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8580>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda84c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda90c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465d720>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00730>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465cf10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8850>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8550>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabf10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaac80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f027d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01450>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabf40>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa710>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaba60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c220>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00be0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ced7eb3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda82e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8520>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8670>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8220>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c070>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f020b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01960>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ced7ebdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8d30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8100>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8370>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8a60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01840>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f00910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8280>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabd30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda84c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda9210>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465e350>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f023e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cf465e650>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8a30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab670>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8130>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8250>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f01f90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f018a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8070>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdaa710>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda81f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda91e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6fca0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f02080>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754ce3f000d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecd6c160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdab790>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecdabb20>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8df0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "Error occurred: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x754cecda8730>: Failed to establish a new connection: [Errno 111] Connection refused'))\n"
     ]
    }
   ],
   "source": [
    "if not cap.isOpened():\n",
    "    print(\"Error: Cannot access the camera.\")\n",
    "    exit()\n",
    "while True:\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        print(\"Error: Failed to capture frame.\")\n",
    "        break\n",
    "    _, img_encoded = cv2.imencode('.jpg', frame)\n",
    "    files = {'file': ('image.jpg', img_encoded.tobytes(), 'image/jpeg')}\n",
    "\n",
    "    try:\n",
    "        response = requests.post(API_URL, files=files)        \n",
    "        if response.status_code == 200:\n",
    "            prediction_data = response.json()\n",
    "            prediction = prediction_data['prediction']\n",
    "            confidence = prediction_data['confidence']\n",
    "            print(f\"Prediction: {prediction}, Confidence: {confidence}\")\n",
    "\n",
    "            # Draw the prediction and confidence text on the frame\n",
    "            text = f\"Prediction: {prediction}, Confidence: {confidence:.2f}\"\n",
    "            cv2.putText(frame, text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 0), 2, cv2.LINE_AA)\n",
    "\n",
    "        else:\n",
    "            print(f\"Error: {response.status_code}, {response.text}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error occurred: {e}\")\n",
    "\n",
    "    cv2.imshow(\"Video\", frame)\n",
    "\n",
    "    # Break the loop if 'q' is pressed\n",
    "    if cv2.waitKey(100) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
